#!/usr/bin/python3
"""Lekce #9 - Uvod do programovani, kontrola cisel"""

     
def hlavni() -> None:
    nactene_udaje = nacitani_udaju("cisla.txt")
    preved_udaje(nactene_udaje)


def nacitani_udaju(soubor: str, rezim="r") -> str:
    with open(soubor, rezim) as txt:
        return txt.readlines()


def preved_udaje(data: list) -> None:
    prevedeno = set()
    
    for udaj in data:
        try:
            udaj = int(udaj.strip())

        except ValueError:
            print(f"NELZE PREVEST --> {udaj}")

        else:
            print(f"{udaj} --> OK, POKRACUJI..")
            prevedeno.add(udaj)

        finally:
            print("-" * 39)


hlavni()

