#!/usr/bin/python3
""" Lekce #3 - Uvod do programovani, Movies """

film1 = {}

film1["JMENO"] = ""
film1["HODNOCENI"] = ""
film1["ROK"] = None
film1["REZISER"] = ""
film1["STOPAZ"] = None
film1["HRAJI"] = ()

film1["JMENO"] = "Shawshank Redemption"
film1["HODNOCENI"] = "93/100"
film1["ROK"] = 1994
film1["REZISER"] = "Frank Darabont"
film1["STOPAZ"] = 144
film1["HRAJI"] = (
    "Tim Robbins",
    "Morgan Freeman",
    "Bob Gunton",
    "William Sadler",
    "Clancy Brown",
    "Gil Bellows",
    "Mark Rolston",
    "James Whitmore",
    "Jeffrey DeMunn",
    "Larry Brandenburg"
)

film1.update({"JMENO": "Shawnshak Redemption"})

film1.pop("JMENO")
film1["JMENO"] = "Shawshank Redemption"

film2 = {
    "JMENO": "The Godfather",
    "HODNOCENI": "92/100",
    "ROK": 1972,
    "REZISER": "Francis Ford Coppola",
    "STOPAZ": 175,
    "HRAJI": (
        "Marlon Brando",
        "Al Pacino",
        "James Caan",
        "Richard S. Castellano",
        "Robert Duvall",
        "Sterling Hayden",
        "John Marley",
        "Richard Conte"
    ),
}

film3 = {
    "JMENO": "The Dark Knight",
    "HODNOCENI": "90/100",
    "ROK": 2008,
    "REZISER": "Christopher Nolan",
    "STOPAZ": 152,
    "HRAJI": (
        "Christian Bale",
        "Heath Ledger",
        "Aaron Eckhart",
        "Michael Caine",
        "Maggie Gyllenhaal",
        "Gary Oldman",
        "Morgan Freeman",
        "Monique Gabriela",
        "Ron Dean",
        "Cillian Murphy"
    ),
}

film4 = {
    "JMENO": "The Prestige",
    "HODNOCENI": "85/100",
    "ROK": 2006,
    "REZISER": "Christopher Nolan",
    "STOPAZ": 130,
    "HRAJI": (
        "Hugh Jackman",
        "Christian Bale",
        "Michael Caine",
        "Piper Perabo",
        "Rebecca Hall",
        "Scarlett Johansson",
        "Samantha Mahurin",
        "David Bowie"
    )
}
filmovy_slovnik = {}
ODDELOVAC = '=' * 76

filmovy_slovnik[film1["JMENO"]] = film1
filmovy_slovnik[film2["JMENO"]] = film2
filmovy_slovnik[film3["JMENO"]] = film3
filmovy_slovnik[film4["JMENO"]] = film4


print(ODDELOVAC)
print("Vitejte v nasi skromne filmove databazi".center(76, " "))

print(
f"""{ODDELOVAC}
VYBERTE KATEGORII:
{ODDELOVAC}
{'VSECHNY FILMY | DETAILY FILMU | SPOLECNI HERCI | VSICHNI REZISERI'.center(76, " ")}
{ODDELOVAC}"""
)

vyber = input("VYBERTE MOZNOST: ").lower()

if vyber == "vsechny filmy":
    print(ODDELOVAC)
    print(f"Mame v nabidce tyto snimky:")
    print(list(filmovy_slovnik.keys()))
    print(ODDELOVAC) 

elif vyber == "detaily filmu":
    print(ODDELOVAC)
    print(list(filmovy_slovnik.keys()))
    print(ODDELOVAC)

    vyber_filmu = input("VYBERTE FILM: ")
    print(ODDELOVAC)
    print(filmovy_slovnik.get(vyber_filmu, "Vami zadany film neni v db"))

elif vyber == "spolecni herci":
    print(ODDELOVAC)
    print(list(filmovy_slovnik.keys()))
    print(ODDELOVAC)

    film1 = input("VYBERTE I. FILM: ")
    film2 = input("VYBERTE II. FILM: ")

    herci_film1 = set(filmovy_slovnik[film1]["HRAJI"])
    herci_film2 = set(filmovy_slovnik[film2]["HRAJI"])

    prunik = herci_film1 & herci_film2
    print(f"SPOLECNI HERCI PRO *{filmovy_slovnik[film1]['JMENO']}* A *{filmovy_slovnik[film2]['JMENO']}*: {prunik}")

elif "reziseri" in vyber:
    print(ODDELOVAC)
    set_reziseri = (
        filmovy_slovnik["The Dark Knight"]["REZISER"],
        filmovy_slovnik["The Godfather"]["REZISER"],
        filmovy_slovnik["Shawshank Redemption"]["REZISER"],
        filmovy_slovnik["The Prestige"]["REZISER"]
    )

    print("VSICHNI REZISERI V NASEM SEZNAMU:")
    print(f"{set(set_reziseri)}")

