#!/usr/bin/python3
""" Lekce #4 - Uvod do programovani, Nakupni kosik """
from pprint import pprint

KOSIK = {}
ODDELOVAC = "=" * 40
POTRAVINY = {
    "mleko": [30, 5],
    "maso": [100, 1],
    "banan": [30, 10],
    "jogurt": [10, 5],
    "chleb": [20, 5],
    "jablko": [10, 10],
    "pomeranc": [15, 10]
}

print("VITEJTE V NASEM VIRTUALNIM OBCHODE!", end=f"\n{ODDELOVAC}\n")
print("VYBERTE SI Z NASEHO ZBOZI:", end=f"\n{ODDELOVAC}\n")
TABULKA = POTRAVINY.copy()

while TABULKA:
    radek_potravina = TABULKA.popitem()
    print(f"POTRAVINA: {radek_potravina[0]},\tCENA: {radek_potravina[1][0]}")
print(ODDELOVAC)

while (vyber_zbozi := input("VYBERTE ZBOZI: ")) != 'exit':
    if vyber_zbozi not in POTRAVINY:
        print("TOTO ZBOZI NEMAME V NABIDKCE!")

    elif vyber_zbozi not in KOSIK and POTRAVINY[vyber_zbozi][1] > 0:
            KOSIK[vyber_zbozi] = [
                POTRAVINY[vyber_zbozi][0],
                1
            ]
            POTRAVINY[vyber_zbozi][1] -= 1
    elif vyber_zbozi in KOSIK and POTRAVINY[vyber_zbozi][1] > 0:
        KOSIK[vyber_zbozi][1] += 1
        POTRAVINY[vyber_zbozi][1] -= 1

    elif POTRAVINY[vyber_zbozi][1] == 0:
        print(f"*{vyber_zbozi.upper()}* NENI SKLADEM!")

else:
    print(ODDELOVAC)
    print("KOSIK JE PLNY! UKONCUJI".center(40, " "), end=f"\n{ODDELOVAC}\n")
    index, vysledek = 0, 0

    while index != len(muj_kosik:=list(KOSIK.values())):
        zbozi = muj_kosik[index]
        cena, pocet = zbozi[0], zbozi[1]
        vysledek += cena * pocet
        index += 1

    else:
        print(
            f"CELKOVA CENA: {vysledek},-".center(40, " "),
            end=f"\n{ODDELOVAC}\n"
        )

